// maps.ts — the single in-code assembler of the cross-mirror "maps sidecar".
//
// R-T7 (audit R3, the agreement-test sweep): several constant tables in this
// extension are mirrored in OTHER languages/artifacts — the Python importer
// (scripts/lib/rdf_gen.py), the served JSON-LD context, the affordance
// descriptor's sub:governs list. Cross-language agreement tests on the Python
// side previously regex-SCRAPED this TypeScript source (test_substrate_mirror_
// consistency.py), which the audit flagged as fragile (F8-python). The fix:
// emit a small committed JSON sidecar (maps.json) from the LIVE TS constants, so
// every consumer (the Python tests, the descriptor agreement test, the CURIE/
// TYPE_MAP agreement tests) parses JSON instead of scraping TS.
//
// Drift-proofing: maps.json is committed AND guarded — test/mapsSidecar.test.ts
// rebuilds this object and asserts it deep-equals the committed file, so the
// sidecar can never silently go stale. Regeneration is wired into `npm run
// build` (the emit-maps step) and exposed as `npm run emit-maps`.

import { CURIE_PREFIX_MAP, TYPE_MAP_TOKENS, MATURITY_MAP_TOKENS } from "./frontmatterProjection.js";
import { BOOTSTRAP_PREDICATE_TO_CLASS } from "./wikilinkProjection.js";
import {
    PAGE_GOVERNED_PREDICATES,
    THING_GOVERNED_PREDICATES,
    WIKI_CLASS_TO_THING_CLASS,
} from "./governedPredicates.js";

// The substrate-internal body-hash stamp predicate (AdmissionFloorStore /
// shape-validator). It is written by the floor under the stamp param, NOT
// projected as governed content, and is deliberately UNADVERTISED in the
// affordance descriptor. Recorded here so the descriptor agreement test can
// assert its ABSENCE from sub:governs (item 4).
export const SUBSTRATE_INTERNAL_PREDICATES: readonly string[] = [
    "https://pod.vardeman.me/vault/ontology/substrate#bodyHash",
];

function sortedUnique(xs: string[]): string[] {
    return [...new Set(xs)].sort();
}

/**
 * The runtime governed-predicate UNION: every predicate the floor validates
 * across the page frame (PAGE_GOVERNED_PREDICATES) and every Thing class
 * (the union of all THING_GOVERNED_PREDICATES value lists). This is the set the
 * affordance descriptor's sub:governs must equal (minus rdf:type, which the
 * descriptor advertises separately as the type axis, and minus the substrate-
 * internal stamp).
 */
export function governedUnion(): string[] {
    const page = PAGE_GOVERNED_PREDICATES.map((n) => n.value);
    const thing = Object.values(THING_GOVERNED_PREDICATES).flatMap((list) =>
        list.map((n) => n.value),
    );
    return sortedUnique([...page, ...thing]);
}

export interface MapsSidecar {
    /** Provenance note for human readers of the committed JSON. */
    _comment: string;
    /** CURIE prefix → namespace IRI (frontmatterProjection CURIE_PREFIXES). */
    curiePrefixes: Record<string, string>;
    /** Frontmatter type token → wiki: class IRI (frontmatterProjection TYPE_MAP). */
    typeMap: Record<string, string>;
    /** Frontmatter maturity token → wiki: lifecycle IRI (frontmatterProjection MATURITY_MAP). */
    maturityMap: Record<string, string>;
    /** Bootstrap predicate IRI → entailed Thing class IRI (wikilinkProjection). */
    bootstrapPredicateToClass: Record<string, string>;
    /**
     * wiki: dispatch class IRI → canonical Thing class IRI. Lets a consumer
     * resolve a TYPE_MAP value (e.g. wiki:Concept) to the sh:targetClass the
     * shape catalog actually governs (skos:Concept) — used by the TYPE_MAP
     * agreement test's "value is governed" check.
     */
    wikiClassToThingClass: Record<string, string>;
    /** Page-frame governed predicates (subject = <>). */
    pageGoverned: string[];
    /** Per-Thing-class governed predicates, keyed by rdf:type IRI. */
    thingGovernedByClass: Record<string, string[]>;
    /** Sorted union of all governed predicates (page + every thing class). */
    governedUnion: string[];
    /** Substrate-internal predicates that stay UNADVERTISED in descriptors. */
    substrateInternal: string[];
}

/** Build the maps-sidecar object from the live TS constants. */
export function buildMaps(): MapsSidecar {
    const thingGovernedByClass: Record<string, string[]> = {};
    for (const [cls, list] of Object.entries(THING_GOVERNED_PREDICATES)) {
        thingGovernedByClass[cls] = list.map((n) => n.value);
    }
    return {
        _comment:
            "GENERATED by `npm run emit-maps` from the live TS constants " +
            "(src/maps.ts buildMaps). Do not hand-edit; run emit-maps. Guarded by " +
            "test/mapsSidecar.test.ts (committed JSON must equal the live source).",
        curiePrefixes: { ...CURIE_PREFIX_MAP },
        typeMap: { ...TYPE_MAP_TOKENS },
        maturityMap: { ...MATURITY_MAP_TOKENS },
        bootstrapPredicateToClass: { ...BOOTSTRAP_PREDICATE_TO_CLASS },
        wikiClassToThingClass: { ...WIKI_CLASS_TO_THING_CLASS },
        pageGoverned: PAGE_GOVERNED_PREDICATES.map((n) => n.value),
        thingGovernedByClass,
        governedUnion: governedUnion(),
        substrateInternal: [...SUBSTRATE_INTERNAL_PREDICATES],
    };
}
